### ISSUE TITLE
Feature: Choose of individual template 

### ISSUE THREAD

**Issue by jankout** [1up-lab/contao-mailchimp#12]
It would be great to have the possibility to choose own individual template. Could you implement this useful feature, please? Thank you.

**Comment by bytehead** [comment]
Implemented in [`3.0.3`](https://github.com/1up-lab/contao-mailchimp/releases/tag/3.0.3) and [`4.1.0`](https://github.com/1up-lab/contao-mailchimp/releases/tag/4.1.0).

**Comment by jankout** [comment]
Thank you very much.
