### ISSUE TITLE
No individual template chooser available

### ISSUE THREAD

**Issue by akroii** [1up-lab/contao-mailchimp#13]
I'm missing the template chooser for signup forms
![bildschirmfoto 2017-12-13 um 16 59 14](https://user-images.githubusercontent.com/8830861/33948383-0149dd3c-e027-11e7-8b0a-095d00614dab.png)

**Comment by bytehead** [comment]
Which version?

**Comment by bytehead** [comment]
Fixed in [`3.1.0`](https://github.com/1up-lab/contao-mailchimp/releases/tag/3.1.0).
Version `2.x` doesn't get support anymore.
