### ISSUE TITLE
Interner Server Error 505

### ISSUE THREAD

**Issue by mrmikeeu** [1up-lab/contao-mailchimp#24]
The service "oneup_contao_mailchimp.listener.dca" was not found or is not public. See https://symfony.com/doc/current/service_container.html#public-versus-private-services

Passiert beim hinzufügen von Liste in Contao Version 4.6.5

**Comment by bytehead** [comment]
Ja, du verwendest Symfony 4.x oder? 
Werde dazu gleich noch einen Fix veröffentlichen.

**Comment by mrmikeeu** [comment]
Gute Frage, wo sehe ich das?

**Comment by bytehead** [comment]
in deiner `composer.json` oder `composer.lock`-Datei.

**Comment by bytehead** [comment]
Fixed in 7def0d9 und Version `4.4.2`.
