### ISSUE TITLE
Language of the Form Fields

### ISSUE THREAD

**Issue by designpilot** [1up-lab/contao-mailchimp#26]
Hello @bytehead 
Why the Language of the HTML5-Placeholder is English and not German. Can I translate that and if so where can I do that?

**Comment by JohnGiddi** [comment]
You have to write it in German at the List Merge-Tags on MailChimp.
Greetings
John Giddi

**Comment by designpilot** [comment]
> You have to write it in German at the List Merge-Tags on MailChimp.
> Greetings
> John Giddi

Hi @JohnGiddi 
So I just have to go into the settings for the lists and click on **List fields and * | MERGE | * tags** and change the value for **English** to **German**? Then I do not have to create new fields again for the German is this correctly?

**Comment by JohnGiddi** [comment]
Yes, change only the field labels of the mege-tags.

**Comment by bytehead** [comment]
Thanks @JohnGiddi for clarifying.
