### ISSUE TITLE
update to guzzlehttp/guzzle ~6.0

### ISSUE THREAD

**Issue by frontendschlampe** [1up-lab/contao-mailchimp#3]
Is it possible to make an update to guzzlehttp/guzzle ~6.0. That would be great! Thank you!

**Comment by bytehead** [comment]
Yes, that's possible! How urgent is it? 😉

**Comment by bytehead** [comment]
I have to update [1up-lab/mailchimp-api-v3](https://github.com/1up-lab/mailchimp-api-v3) as well.

**Comment by frontendschlampe** [comment]
It's urgent! ;-) As always!

**Comment by bytehead** [comment]
Fixed in 72d8bbb.
