### ISSUE TITLE
Contao 4.11.2 and Symfony 5.x

### ISSUE THREAD

**Issue by jankout** [1up-lab/contao-mailchimp#31]
Hello, 

I have a problem with your extension with Contao 4.11.2 and Symfony 5.x. 

```
Attempted to load class "Event" from namespace "Symfony\Component\EventDispatcher".
Did you forget a "use" statement for e.g. "Symfony\Contracts\EventDispatcher\Event", "Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Event", "Laminas\EventManager\Event", "FOS\HttpCache\Event" or "Eluceo\iCal\Component\Event"?
```
<img width="1079" alt="Snímek obrazovky 2021-03-30 v 15 00 06" src="https://user-images.githubusercontent.com/3715050/113001809-1253af80-9169-11eb-989a-04b5623691ee.png">

**Comment by bytehead** [comment]
Closing in favor of #32

**Comment by bytehead** [comment]
Can you check [4.4.6](https://github.com/1up-lab/contao-mailchimp/releases/tag/4.4.6)?

**Comment by jankout** [comment]
A new error occurs
<img width="1095" alt="Snímek obrazovky 2021-03-30 v 16 59 59" src="https://user-images.githubusercontent.com/3715050/113020711-c3af1100-917a-11eb-9d48-e738dc314818.png">

**Comment by bytehead** [comment]
Yep, my fault 🙈 Check [4.4.7](https://github.com/1up-lab/contao-mailchimp/releases/tag/4.4.7).

**Comment by jankout** [comment]
Super, it works. :-) Thank you very much.

**Comment by bytehead** [comment]
Nice 🎉 Thanks for reporting!
