### ISSUE TITLE
Compatibility with ajax form

### ISSUE THREAD

**Issue by jankout** [1up-lab/contao-mailchimp#33]
Hello, 

it would be great to use [ajax form](https://github.com/terminal42/contao-ajaxform) instead of forwarding to another page. Would it be possible, please?

**Comment by fritzmg** [comment]
Once https://github.com/1up-lab/contao-mailchimp/pull/35 is merged you can basically do this. You just have to configure the form manually then.

**Comment by jankout** [comment]
That sounds amazing. Thank you very much!

**Comment by bytehead** [comment]
#35 has been merged in the meanwhile.
