### ISSUE TITLE
Error mit dem subscribe-modul und PHP 8.1  & Contao 4.13.14

### ISSUE THREAD

**Issue by srhinow** [1up-lab/contao-mailchimp#43]
Hallo,
wenn ich den Debug-Modus anschalte und auf der Website das subscribe-Formular als Modul eingebunden ist kommt folgende Meldung:
```
ErrorException                    <span class="icon icon-close"><svg width="1792" height="1792" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"></svg></span>

 
--
ErrorException: 

Warning: Undefined property: stdClass::$options    at vendor/oneup/contao-mailchimp/src/Module/ModuleSubscribe.php:264   at Oneup\Contao\MailChimpBundle\Module\ModuleSubscribe->addFieldToForm()      (vendor/oneup/contao-mailchimp/src/Module/ModuleSubscribe.php:86)   at Oneup\Contao\MailChimpBundle\Module\ModuleSubscribe->compile()      (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:214)   at Contao\Module->generate()      (vendor/oneup/contao-mailchimp/src/Module/ModuleSubscribe.php:46)   at Oneup\Contao\MailChimpBundle\Module\ModuleSubscribe->generate()      (vendor/contao/core-bundle/src/Resources/contao/elements/ContentModule.php:98)   at Contao\ContentModule->generate()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:616)   at Contao\Controller::getContentElement()      (vendor/srhinow/teaser-manager/classes/TeaserManager.php:182)   at TeaserManager->getTeaserContentHTML()      (vendor/srhinow/teaser-manager/classes/TeaserManager.php:144)   at TeaserManager->getTeaserHtml()      (vendor/srhinow/teaser-manager/classes/TeaserManager.php:78)   at TeaserManager->getHtmlFromTeaserGroup()      (vendor/srhinow/teaser-manager/modules/ModuleTeaserGroup.php:66)   at ModuleTeaserGroup->compile()      (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:214)   at Contao\Module->generate()      (vendor/srhinow/teaser-manager/modules/ModuleTeaserGroup.php:49)   at ModuleTeaserGroup->generate()      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:435)   at Contao\Controller::getFrontendModule()      (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:190)   at Contao\PageRegular->prepare()      (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:60)   at Contao\PageRegular->getResponse()      (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:320)   at Contao\FrontendIndex->renderPage()      (vendor/symfony/http-kernel/HttpKernel.php:163)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw()      (vendor/symfony/http-kernel/HttpKernel.php:75)   at Symfony\Component\HttpKernel\HttpKernel->handle()      (vendor/symfony/http-kernel/Kernel.php:202)   at Symfony\Component\HttpKernel\Kernel->handle()      (web/index.php:44)
```

**Comment by bytehead** [comment]
Welche Version?

**Comment by srhinow** [comment]
Version 4.7.0

**Comment by srhinow** [comment]
und hier ist das was in fields zur eingesetzten mailchimpList drin steht:
```json
[
    {
        "id":3,
        "tag":"ADDRESS",
        "name":"Address",
        "type":"address",
        "displayOrder":4,
        "required":false,
        "options":{
            "default_country":164
        },
        "public":false,
        "default":""
    },
    {
        "id":5,
        "tag":"BIRTHDAY",
        "name":"Birthday",
        "type":"birthday",
        "displayOrder":6,
        "required":false,
        "options":{
            "date_format":"MM\/DD"
        },
        "public":true,
        "default":""
    },
    {
        "id":1,
        "tag":"FNAME",
        "name":"First Name",
        "type":"text",
        "displayOrder":2,
        "required":false,
        "options":{
            "size":25
        },
        "public":true,
        "default":""
    },
    {
        "id":2,
        "tag":"LNAME",
        "name":"Last Name",
        "type":"text",
        "displayOrder":3,
        "required":false,
        "options":{
            "size":25
        },
        "public":true,
        "default":""
    },
    {
        "id":4,
        "tag":"PHONE",
        "name":"Phone Number",
        "type":"phone",
        "displayOrder":5,
        "required":false,
        "options":{
            
        },
        "public":false,
        "default":""
    }
]
```

**Comment by bytehead** [comment]
~~Welche Contao Version?~~ nevermind - hab's grad im Titel gesehen :)

**Comment by bytehead** [comment]
@srhinow kannst du mal den branch [`fix/undefined-property`](https://github.com/1up-lab/contao-mailchimp/tree/fix/undefined-property) in deinem `composer.json` requiren (`dev-fix/undefined-property`) und prüfen, ob das den Fehler behebt?

**Comment by srhinow** [comment]
nein leider noch nicht:

`ErrorException:
Warning: Undefined property: stdClass::$options

  at vendor/oneup/contao-mailchimp/src/Module/ModuleSubscribe.php:264
  at Oneup\Contao\MailChimpBundle\Module\ModuleSubscribe->addFieldToForm()
     (vendor/oneup/contao-mailchimp/src/Module/ModuleSubscribe.php:86)
  at Oneup\Contao\MailChimpBundle\Module\ModuleSubscribe->compile()
     (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:214)
  at Contao\Module->generate()
     (vendor/oneup/contao-mailchimp/src/Module/ModuleSubscribe.php:46)
  at Oneup\Contao\MailChimpBundle\Module\ModuleSubscribe->generate()
     (vendor/contao/core-bundle/src/Resources/contao/elements/ContentModule.php:98)
  at Contao\ContentModule->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:616)
  at Contao\Controller::getContentElement()
     (vendor/srhinow/teaser-manager/classes/TeaserManager.php:182)
  at TeaserManager->getTeaserContentHTML()
     (vendor/srhinow/teaser-manager/classes/TeaserManager.php:144)
  at TeaserManager->getTeaserHtml()
     (vendor/srhinow/teaser-manager/classes/TeaserManager.php:78)
  at TeaserManager->getHtmlFromTeaserGroup()
     (vendor/srhinow/teaser-manager/modules/ModuleTeaserGroup.php:66)
  at ModuleTeaserGroup->compile()
     (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:214)
  at Contao\Module->generate()
     (vendor/srhinow/teaser-manager/modules/ModuleTeaserGroup.php:49)
  at ModuleTeaserGroup->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:435)
  at Contao\Controller::getFrontendModule()
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:190)
  at Contao\PageRegular->prepare()
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:60)
  at Contao\PageRegular->getResponse()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:320)
  at Contao\FrontendIndex->renderPage()
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:44) `

**Comment by bytehead** [comment]
Das kann fast nicht sein 🤔 

Wie sieht die Zeile `vendor/oneup/contao-mailchimp/src/Module/ModuleSubscribe.php:264` bei dir aus?

**Comment by srhinow** [comment]
![image](https://user-images.githubusercontent.com/741418/212100539-97e15688-b431-4a49-a1b6-8e4ee3384bb3.png)

**Comment by bytehead** [comment]
Achso 🤦  lesen hilft natürlich.

**Comment by bytehead** [comment]
Kannst du nochmals updaten?

**Comment by srhinow** [comment]
jetzt geht es in Zeile 282 weiter:
![image](https://user-images.githubusercontent.com/741418/212101853-85b3d198-7dff-40ed-9914-5146c683d934.png)

**Comment by bytehead** [comment]
Was macht denn da die MailChimp API mit den Daten? Laut deinem [Daten](https://github.com/1up-lab/contao-mailchimp/issues/43#issuecomment-1380413176) ist ja in jedem Feld ein default gesetzt...

**Comment by srhinow** [comment]
Die ganze Prozedur mache ich auch in den letzten Wochen für diverse Projekt-Bundles für >=PHP 8

**Comment by bytehead** [comment]
🤯 Dann halt Schritt für Schritt - kannst du nochmals updaten? :)

**Comment by srhinow** [comment]
jetzt geht es im template weiter:
![image](https://user-images.githubusercontent.com/741418/212106463-74b4a85d-f16e-47be-91bf-9408a9bcaa71.png)

**Comment by bytehead** [comment]
Fixed in [95544ea](https://github.com/1up-lab/contao-mailchimp/pull/44/commits/95544eaf98bb61d5c523f797582609379b2ff5b4).

**Comment by srhinow** [comment]
jetzt passt es und es wird ohne Fehler angezeigt. Magste das taggen?

**Comment by bytehead** [comment]
Klar doch! :) Danke fürs melden!

**Comment by bytehead** [comment]
4.7.1 ist da! 🥳

**Comment by srhinow** [comment]
Ich danke dir fürs schnelle beheben.
