### ISSUE TITLE
can't install Plugin v4.8.1

### ISSUE THREAD

**Issue by sw-health** [1up-lab/contao-mailchimp#47]
Hello,
I tried to install the Mailchimp Plugin via the Contao Manager (v 1.6.3) within our Contao Installation (v 4.13.26).
I got the following error messages:

> $ /usr/local/php81/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -ddisplay_errors=0 -ddisplay_startup_errors=0 -derror_reporting=0 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /CMS/contao/.../contao4/public/contao-manager.phar.php composer require oneup/contao-mailchimp --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction
> 
> Info from https://repo.packagist.org: #StandWithUkraine
> Using version ^4.8 for oneup/contao-mailchimp
> /var/www/vhosts/hosting169517.ae85e.netcup.net/httpdocs/CMS/contao/sanawork/contao4/composer.json has been updated
> 
> # Process terminated with exit code 0
> # Result: OK
> 
> > Resolving dependencies using Composer Cloud v3.6.0-1-g9d9036c
> 
> [7.4MiB/0.18s] Loading composer repositories with package information
> [67.1MiB/8.43s] Updating dependencies
> [82.7MiB/8.60s] Your requirements could not be resolved to an installable set of packages.
> [82.7MiB/8.60s] 
>   Problem 1
>     - oneup/mailchimp-api-v3[2.7.0, ..., 2.7.1] require guzzlehttp/guzzle ^7.4.5 -> found guzzlehttp/guzzle[7.4.5, ..., 7.7.0] but these were not loaded, likely because it conflicts with another require.
>     - oneup/contao-mailchimp[4.8.0, ..., 4.8.1] require oneup/mailchimp-api-v3 ^2.7 -> satisfiable by oneup/mailchimp-api-v3[2.7.0, 2.7.1].
>     - Root composer.json requires oneup/contao-mailchimp ^4.8 -> satisfiable by oneup/contao-mailchimp[4.8.0, 4.8.1].
> 
> [82.7MiB/8.60s] Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
> [38.5MiB/8.62s] Memory usage: 38.54MB (peak: 191.83MB), time: 8.63s.
> [38.5MiB/8.62s] Finished Composer Cloud resolving.
> 
> # Cloud Job ID flJIWXPgDxUnAWilBmJUsFwYiGBlDV83jcRQE4pyRPNo7aGnHZwnJj1TV3Xfa5QU4gXqQnf47B3MotztFgBdN1wmQUNsV3yclS9o failed

Could you help me out and fix this issue?
Thank you very much.

**Comment by bytehead** [comment]
> Problem 1
> - oneup/mailchimp-api-v3[2.7.0, ..., 2.7.1] require guzzlehttp/guzzle ^7.4.5 -> found guzzlehttp/guzzle[7.4.5, ..., 7.7.0] but these were not loaded, likely because it conflicts with another require.

Some other package does require `guzzlehttp/guzzle` in a different version  and therefore Composer cannot solve the requirements.

If you're able to run Composer on command line, you could try following command: `composer why guzzlehttp/guzzle`

This should output the reason, why `guzzlehttp/guzzle` is already installed in a different version.

I don't know how to figure that out with the Contao Manager, as I never used it.

**Comment by bytehead** [comment]
But there is nothing we can fix on our side so far.
