### ISSUE TITLE
Any chance for Contao 5.3 // 4.13 ?

### ISSUE THREAD

**Issue by k-webdesign** [1up-lab/contao-mailchimp#49]
Hey Dave,

any chance this will work with Contao 5.3 - or at least 4.13?

**Comment by bytehead** [comment]
It should work for 4.13 already. We will support 5.x next.

**Comment by bytehead** [comment]
See #50

**Comment by bytehead** [comment]
@k-webdesign `4.9.0` supports now Contao 5.
