### ISSUE TITLE
Hidden fields not hidden? Other Input Types supported?

### ISSUE THREAD

**Issue by denniserdmann** [1up-lab/contao-mailchimp#5]
Moin!

I'm working with some hidden fields in Mailchimp. Unfortunately, they appear in Contao. On the other side, i have a checkbox field that doesn't show up. Any ideas?

Grüße,
Dennis

**Comment by bytehead** [comment]
Hi!

Hmm, not yet :)
Can you describe your setup or upload a screenshot from the field configuration at mailchimp?

**Comment by bytehead** [comment]
I'm actually not sure, if checkboxes are supported at the moment: https://github.com/1up-lab/contao-mailchimp/blob/master/src/MailChimp/Module/ModuleSubscribe.php#L124-L219

**Comment by denniserdmann** [comment]
Sure,

here is my current setup: 
![bildschirmfoto 2017-02-21 um 07 59 49](https://cloud.githubusercontent.com/assets/3773697/23153993/d7dab0c4-f80b-11e6-9de9-79f658c0af1d.png)

The checkbox-input is a group i created, which will then be added to the form.

**Comment by bytehead** [comment]
Thank you for reporting, I'll investigate this.

**Comment by bytehead** [comment]
I've looked into it.
The hidden fields will be fixed in the next release 🙂 

But I didn't get how you create checkboxes under `List`-> `Settings` -> `List fields and *|MERGE|* tags`.  I saw you can create checkboxes under `List` -> `Signup Forms`, but we don't have any API access on this forms.

**Comment by bytehead** [comment]
The checkboxes are for group separations. Will have to dig into https://developer.mailchimp.com/documentation/mailchimp/reference/lists/interest-categories/, there is maybe a possibility to add those to the subscribe form as well.

**Comment by bytehead** [comment]
Hidden fields will work with [2.2.0](https://github.com/1up-lab/contao-mailchimp/releases/tag/2.2.0).

**Comment by denniserdmann** [comment]
Great,

i was using another contao mail chimp extension in the past, which had the same problem with interests/categories. But maybe „you have a little bit lucky“ ;-)

**Comment by fritzmg** [comment]
@bytehead we also need the group feature. Any plans or ideas yet?

**Comment by bytehead** [comment]
Not yet, lost the focus a bit on this topic. I don't even know if it's possible to get them.

**Comment by fritzmg** [comment]
It should be possible. There is a basic (WordPress -_-) example here: https://rudrastyh.com/mailchimp-api/interest-groups.html

If you don't have anything planned, we'll probably provide a PR ;)

**Comment by bytehead** [comment]
PR is highly welcome 😎

**Comment by fritzmg** [comment]
PRs added: https://github.com/1up-lab/contao-mailchimp/pull/15, https://github.com/1up-lab/mailchimp-api-v3/pull/4

**Comment by bytehead** [comment]
Version `4.2.0` is released. Thanks for contributing!
