### ISSUE TITLE
Fatal error in Contao 3.5, because pathwork/utf8 dependency is missing

### ISSUE THREAD

**Issue by bezin** [1up-lab/contao-mailchimp#8]
Hi there, 

when you install this extension for Contao 3.5, your setup may be missing pathwork/utf8 and hence throws a fatal error in the backend. Should we include this as dependency in the composer.json?

Cheerio

**Comment by bytehead** [comment]
That's actually true. Introduced here: https://github.com/1up-lab/contao-mailchimp/commit/7db6ebe841a0f266dde4f8ff3079734b518d79c7#diff-8ce91b000ff98cd1a556a946fbc114b4R13. I'll come up with a fix asap.

**Comment by bytehead** [comment]
Please check if `3.0.2` fixes the problem. Thanks for reporting!
